name: flutter_response_status
description: Flutter_response_status is a package that to standardize responses in dart.
version: 2.0.0
author: Danilo Santos <danilocarsan@gmail.com>
homepage: https://github.com/DaniloCarSan/flutter_response_status

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

